spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
      database: journaldb
Server:
  port: 8080
  Servelet:
    context-path: /journal

logging:
  level:
    net:
      BabaJI:
        journalApp: DEBUG