spring:
  data:
    redis:
      url: ${REDIS_URI}
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
      database: journaldb

  mail:
    port : 587
    host: smtp.gmail.com
    username: ${MAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

Server:
  port: 8080
  Servelet:
    context-path: /journal

logging:
  level:
    net:
      BabaJI:
        journalApp: DEBUG

weather:
  api:
    key: ${API_KEY}

