spring:
  data:
    redis:
      url: ${REDIS_URI}
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
      database: journaldb

  mail:
    port: 587
    host: smtp.gmail.com
    username: ${MAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: weekly-sentiment
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    properties:
      session.timeout.ms: 45000

Server:
  port: 8080
  Servelet:
    context-path: /journal

logging:
  level:
    net:
      BabaJI:
        journalApp: DEBUG

weather:
  api:
    key: ${API_KEY}
